services:
  caddy:
    image: caddy:alpine
    container_name: caddy-proxy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"   # HTTP/3
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
    dns:
      - 8.8.8.8
      - 1.1.1.1
    networks:
      - webnet
    depends_on:
      - portfolio
 
  portfolio:
    image: sulthangamer123/porfolio-app:230b42fd86b6ca077bb77897a30ed57e83ec8dae

    container_name: portfolio
    restart: unless-stopped
    expose:
      - "80"
    networks:
      - webnet
 
volumes:
  caddy_data:
  caddy_config:
 
networks:
  webnet:
    driver: bridge
 
